apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: project-x
  description: Project X monorepo
  annotations:
    github.com/project-slug: sayabasu/Project-X
spec:
  type: service
  owner: team-project-x
  lifecycle: experimental
