const nodemailer = require('nodemailer');
const config = require('../config');

const transporter = nodemailer.createTransport({
  host: config.smtp.host,
  port: config.smtp.port,
  secure: config.smtp.secure,
  auth: {
    user: config.smtp.user,
    pass: config.smtp.pass,
  },
});

const sendTestEmail = async (to, context = {}) => {
  const subject = `Project X Connectivity Test - ${new Date().toISOString()}`;
  const textBody = `This is a test email generated by Project X. Context: ${JSON.stringify(context)}`;

  return transporter.sendMail({
    from: config.smtp.from,
    to,
    subject,
    text: textBody,
  });
};

module.exports = {
  transporter,
  sendTestEmail,
};
